<?php

namespace App\Tests\Integration\Repository;

use App\Entity\Set;
use App\Repository\SetRepository;
use App\Tests\DatabaseResetTrait;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

/**
 * Generated by JetBrains AI
 */
class SetRepositoryTest extends KernelTestCase
{
    use DatabaseResetTrait;

    private EntityManagerInterface $entityManager;
    private SetRepository $setRepository;

    protected function setUp(): void
    {
        self::bootKernel();
        $this->entityManager = $this->resetDatabase();
        $this->setRepository = $this->entityManager->getRepository(Set::class);
    }

    protected function tearDown(): void
    {
        $this->resetDatabase();
        parent::tearDown();
    }

    public function testDoesAlreadyExistReturnsTrueForMatchingNumber(): void
    {
        $this->persistSet(4321, 'Millennium Falcon');

        $this->assertTrue($this->setRepository->doesAlreadyExist('4321', 'Some other name'));
    }

    public function testDoesAlreadyExistReturnsTrueForMatchingName(): void
    {
        $this->persistSet(4321, 'Millennium Falcon');

        $this->assertTrue($this->setRepository->doesAlreadyExist('9999', 'Millennium Falcon'));
    }

    public function testDoesAlreadyExistReturnsFalseWhenNeitherMatches(): void
    {
        $this->persistSet(4321, 'Millennium Falcon');

        $this->assertFalse($this->setRepository->doesAlreadyExist('9999', 'X-Wing'));
    }

    public function testDoesAlreadyExistReturnsFalseWhenNameIsOmitted(): void
    {
        $this->persistSet(4321, 'Millennium Falcon');

        $this->assertFalse($this->setRepository->doesAlreadyExist('9999'));
    }

    private function persistSet(int $number, string $name): Set
    {
        $set = new Set();
        $set->setNumber($number);
        $set->setName($name);
        $this->entityManager->persist($set);
        $this->entityManager->flush();

        return $set;
    }
}
