<?php

namespace App\Tests;

use Doctrine\ORM\EntityManagerInterface;

/**
 * Clears the App entity tables before and after each test, so no test has
 * to worry about state left behind by another one.
 *
 * A transaction-per-test wrapped in a rollback was tried first but proved
 * unreliable with WebTestCase: reusing services tagged "kernel.reset"
 * across the requests a single test issues can silently detach from a
 * manually held transaction. Deleting rows directly is slower but robust.
 *
 * Generated by JetBrains AI
 */
trait DatabaseResetTrait
{
    protected function resetDatabase(): EntityManagerInterface
    {
        $entityManager = static::getContainer()->get(EntityManagerInterface::class);
        $connection = $entityManager->getConnection();
        $connection->executeStatement('DELETE FROM manual');
        $connection->executeStatement('DELETE FROM "set"');
        $entityManager->clear();

        return $entityManager;
    }
}
