<?php

namespace App\Tests\Integration\Controller;

use App\Service\SetLookupService;
use App\Tests\Fake\FakeSetLookupService;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Response;

/**
 * Generated by JetBrains AI
 */
class ImportControllerAutoloadTest extends WebTestCase
{
    public function testAutoloadReturnsJsonFromLookupService(): void
    {
        $client = static::createClient();
        self::getContainer()->set(SetLookupService::class, FakeSetLookupService::returning([
            'title' => 'X-Wing Starfighter',
            'documents' => ['https://example.com/9493-1.pdf'],
        ]));

        $client->request('GET', '/import/autoload/9493');

        $this->assertResponseIsSuccessful();
        $this->assertJsonStringEqualsJsonString(
            '{"title":"X-Wing Starfighter","documents":["https:\/\/example.com\/9493-1.pdf"]}',
            $client->getResponse()->getContent(),
        );
    }

    public function testAutoloadReturns500WhenLookupProcessFails(): void
    {
        $client = static::createClient();
        self::getContainer()->set(SetLookupService::class, FakeSetLookupService::failing());

        $client->request('GET', '/import/autoload/9493');

        $this->assertResponseStatusCodeSame(Response::HTTP_INTERNAL_SERVER_ERROR);
    }
}
