<?php

namespace App\Tests\Integration\Controller;

use App\Entity\Set;
use App\Tests\DatabaseResetTrait;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Response;

/**
 * Generated by JetBrains AI
 */
class ImportControllerTest extends WebTestCase
{
    use DatabaseResetTrait;

    private EntityManagerInterface $entityManager;

    protected function setUp(): void
    {
        parent::setUp();
        static::createClient();
        $this->entityManager = $this->resetDatabase();
    }

    protected function tearDown(): void
    {
        $this->resetDatabase();
        parent::tearDown();
    }

    public function testImportFormIsRenderedSuccessfully(): void
    {
        static::getClient()->request('GET', '/import');

        $this->assertResponseIsSuccessful();
        $this->assertSelectorExists('#set_form');
    }

    public function testSubmittingWithoutRequiredNameReRendersFormWithErrors(): void
    {
        $client = static::getClient();
        $crawler = $client->request('GET', '/import');

        $form = $crawler->selectButton('Speichern')->form([
            'set_form[number]' => '1234',
            'set_form[name]' => '',
        ]);
        $client->submit($form);

        $this->assertResponseStatusCodeSame(Response::HTTP_UNPROCESSABLE_ENTITY);
        $this->assertSame(0, $this->countSets());
    }

    public function testSubmittingKnownDuplicateNumberShowsError(): void
    {
        $this->persistSet(4321, 'Millennium Falcon');

        $client = static::getClient();
        $crawler = $client->request('GET', '/import');

        $form = $crawler->selectButton('Speichern')->form([
            'set_form[number]' => '4321',
            'set_form[name]' => 'Neuer Name',
        ]);
        $client->submit($form);

        $this->assertStringContainsString('existiert bereits', $client->getResponse()->getContent());
        $this->assertSame(1, $this->countSets());
    }

    private function persistSet(int $number, string $name): Set
    {
        $set = new Set();
        $set->setNumber($number);
        $set->setName($name);
        $this->entityManager->persist($set);
        $this->entityManager->flush();

        return $set;
    }

    private function countSets(): int
    {
        return (int) $this->entityManager->getRepository(Set::class)->count([]);
    }
}
