<?php

namespace App\Tests\Integration\Controller;

use App\Entity\Manual;
use App\Entity\Set;
use App\Tests\DatabaseResetTrait;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * Generated by JetBrains AI
 */
class IndexControllerTest extends WebTestCase
{
    use DatabaseResetTrait;

    private EntityManagerInterface $entityManager;

    protected function setUp(): void
    {
        parent::setUp();
        static::createClient();
        $this->entityManager = $this->resetDatabase();
    }

    protected function tearDown(): void
    {
        $this->resetDatabase();
        parent::tearDown();
    }

    public function testIndexPageIsSuccessfulWithoutAnySets(): void
    {
        static::getClient()->request('GET', '/');

        $this->assertResponseIsSuccessful();
    }

    public function testSetsAreRenderedAlphabeticallyWithCorrectFileCount(): void
    {
        $this->persistSetWithManuals('Y-Wing', 9495, 1);
        $this->persistSetWithManuals('X-Wing', 9493, 2);

        $crawler = static::getClient()->request('GET', '/');

        $this->assertResponseIsSuccessful();

        // the title is only printed once per set (on its first manual), the
        // rest render an empty ".manual-title" placeholder
        $titles = array_values(array_filter($crawler->filter('.manual-title')->each(
            static fn ($node): string => trim($node->text()),
        )));
        $this->assertSame(['X-Wing 9493', 'Y-Wing 9495'], $titles);

        $this->assertCount(3, $crawler->filter('.manual-box'));
    }

    private function persistSetWithManuals(string $name, int $number, int $manualCount): Set
    {
        $set = new Set();
        $set->setName($name);
        $set->setNumber($number);
        $this->entityManager->persist($set);

        for ($i = 0; $i < $manualCount; ++$i) {
            $manual = new Manual();
            $manual->setUrl('https://example.com/' . $number . '-' . $i . '.pdf');
            $set->addManual($manual);
        }

        $this->entityManager->flush();

        return $set;
    }
}
