<?php

namespace App\Tests\Integration\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Response;

/**
 * The "symfony security:check" callback the controller runs is not
 * guaranteed to succeed in a test/CI environment (the "symfony" CLI binary
 * may not be installed there), so this only asserts that the status page
 * always renders instead of crashing, whichever way the checks turn out.
 *
 * Generated by JetBrains AI
 */
class StatusControllerTest extends WebTestCase
{
    public function testStatusPageRendersWithoutThrowing(): void
    {
        $client = static::createClient();
        $client->request('GET', '/status');

        $this->assertContains(
            $client->getResponse()->getStatusCode(),
            [Response::HTTP_OK, Response::HTTP_SERVICE_UNAVAILABLE],
        );
        $this->assertSelectorTextContains('body', 'Application Status');
    }
}
