<?php

namespace App\Tests\Unit\Service;

use App\Service\DownloadService;
use PHPUnit\Framework\TestCase;

/**
 * downloadManualFile() only ever cares about reading bytes from a URL and
 * writing them to a path, so it is exercised for real against file:// URLs
 * pointing at the fixture PDF, instead of mocking around the network.
 *
 * Generated by JetBrains AI
 */
class DownloadServiceTest extends TestCase
{
    private string $fixturePdf;
    private string $fixtureContent;

    /** @var list<string> */
    private array $filesToCleanUp = [];

    protected function setUp(): void
    {
        $this->fixturePdf = __DIR__ . '/../../Fixtures/manual.pdf';
        $this->fixtureContent = file_get_contents($this->fixturePdf);
    }

    protected function tearDown(): void
    {
        foreach ($this->filesToCleanUp as $file) {
            if (file_exists($file)) {
                unlink($file);
            }
        }
    }

    public function testGetSaveFilenameLowercasesAndStripsUnsafeCharacters(): void
    {
        $service = new DownloadService();

        $this->assertSame(
            'legoinstructions123.pdf',
            $service->getSaveFilename('LEGO Instructions_123!.pdf')
        );
    }

    public function testGetSaveFilenameKeepsDigitsAndDots(): void
    {
        $service = new DownloadService();

        $this->assertSame('6.28.0.pdf', $service->getSaveFilename('6.28.0.pdf'));
    }

    public function testDownloadManualFileWritesContentToGivenPath(): void
    {
        $service = new DownloadService();
        $targetPath = sys_get_temp_dir() . '/' . uniqid('download-service-test-', true) . '.pdf';
        $this->filesToCleanUp[] = $targetPath;

        $result = $service->downloadManualFile('file://' . $this->fixturePdf, $targetPath);

        $this->assertSame($targetPath, $result);
        $this->assertSame($this->fixtureContent, file_get_contents($targetPath));
    }

    public function testDownloadManualFileGeneratesSanitizedFilenameWhenPathOmitted(): void
    {
        $service = new DownloadService();

        $result = $service->downloadManualFile('file://' . $this->fixturePdf);
        $this->filesToCleanUp[] = $result;

        $this->assertSame(sys_get_temp_dir() . '/manual.pdf', $result);
        $this->assertSame($this->fixtureContent, file_get_contents($result));
    }

    public function testDownloadManualFileAppendsPdfExtensionWhenSourceHasNone(): void
    {
        $sourceWithoutExtension = sys_get_temp_dir() . '/' . uniqid('download-service-source-', true);
        file_put_contents($sourceWithoutExtension, $this->fixtureContent);
        $this->filesToCleanUp[] = $sourceWithoutExtension;

        $service = new DownloadService();
        $result = $service->downloadManualFile('file://' . $sourceWithoutExtension);
        $this->filesToCleanUp[] = $result;

        $this->assertStringEndsWith('.pdf', $result);
    }
}
