<?php

namespace App\Tests\Unit\Service;

use App\Service\PdfService;
use PHPUnit\Framework\TestCase;
use RuntimeException;

/**
 * Exercises the real Imagick/Ghostscript pipeline against a small fixture
 * PDF (tests/Fixtures/manual.pdf) instead of mocking it, since both are
 * genuinely installed in the runtime image (see docker/Dockerfile).
 *
 * Generated by JetBrains AI
 */
class PdfServiceTest extends TestCase
{
    private string $fixturePdf;
    private string $outputJpg;

    protected function setUp(): void
    {
        $this->fixturePdf = __DIR__ . '/../../Fixtures/manual.pdf';
        $this->outputJpg = sys_get_temp_dir() . '/' . uniqid('pdf-service-test-', true) . '.jpg';
    }

    protected function tearDown(): void
    {
        if (file_exists($this->outputJpg)) {
            unlink($this->outputJpg);
        }
    }

    public function testExtractCoverProducesAJpegScaledTo300pxWide(): void
    {
        $service = new PdfService();

        $service->extractCover($this->fixturePdf, $this->outputJpg);

        $this->assertFileExists($this->outputJpg);
        $imageSize = getimagesize($this->outputJpg);
        $this->assertNotFalse($imageSize);
        $this->assertSame(IMAGETYPE_JPEG, $imageSize[2]);
        $this->assertSame(300, $imageSize[0]);
    }

    public function testExtractCoverThrowsWhenPdfDoesNotExist(): void
    {
        $service = new PdfService();

        $this->expectException(RuntimeException::class);

        $service->extractCover(sys_get_temp_dir() . '/does-not-exist.pdf', $this->outputJpg);
    }
}
