<?php

namespace App\Tests\Unit\Entity;

use App\Entity\Manual;
use App\Entity\Set;
use LogicException;
use PHPUnit\Framework\TestCase;

/**
 * Generated by JetBrains AI
 */
class ManualTest extends TestCase
{
    public function testGetPdfFileNameBuildsNameFromSetNumberIdAndUrlExtension(): void
    {
        $set = new Set();
        $set->setNumber(42);

        $manual = new Manual();
        $manual->setSet($set);
        $manual->setId(7);
        $manual->setUrl('https://example.com/path/to/instructions.pdf');

        $this->assertSame('42_7.pdf', $manual->getPdfFileName());
    }

    public function testGetPdfFileNameDefaultsToPdfExtensionWhenUrlHasNone(): void
    {
        $set = new Set();
        $set->setNumber(42);

        $manual = new Manual();
        $manual->setSet($set);
        $manual->setId(7);
        $manual->setUrl('https://example.com/download');

        $this->assertSame('42_7.pdf', $manual->getPdfFileName());
    }

    public function testGetPdfFileNameThrowsWhenSetHasNoNumber(): void
    {
        $manual = new Manual();
        $manual->setSet(new Set());
        $manual->setId(7);
        $manual->setUrl('https://example.com/instructions.pdf');

        $this->expectException(LogicException::class);
        $this->expectExceptionMessageIs('Set has no number');

        $manual->getPdfFileName();
    }

    public function testGetPdfFileNameThrowsWhenManualHasNoId(): void
    {
        $set = new Set();
        $set->setNumber(42);

        $manual = new Manual();
        $manual->setSet($set);
        $manual->setUrl('https://example.com/instructions.pdf');

        $this->expectException(LogicException::class);

        $manual->getPdfFileName();
    }

    public function testGetCoverFileNameAppendsJpgToPdfFileName(): void
    {
        $set = new Set();
        $set->setNumber(42);

        $manual = new Manual();
        $manual->setSet($set);
        $manual->setId(7);
        $manual->setUrl('https://example.com/instructions.pdf');

        $this->assertSame('42_7.pdf.jpg', $manual->getCoverFileName());
    }

    public function testToStringReturnsUrl(): void
    {
        $manual = new Manual();
        $manual->setUrl('https://example.com/instructions.pdf');

        $this->assertSame('https://example.com/instructions.pdf', (string) $manual);
    }
}
