<?php

namespace App\Tests\Unit\Entity;

use App\Entity\Manual;
use App\Entity\Set;
use PHPUnit\Framework\TestCase;

/**
 * Generated by JetBrains AI
 */
class SetTest extends TestCase
{
    public function testToStringContainsNumberNameAndManualCount(): void
    {
        $set = new Set();
        $set->setNumber(4321);
        $set->setName('Millennium Falcon');
        $set->addManual(new Manual());
        $set->addManual(new Manual());

        $this->assertSame('4321 Millennium Falcon (2 Dokumente)', (string) $set);
    }

    public function testAddManualSetsBackReferenceToSet(): void
    {
        $set = new Set();
        $manual = new Manual();

        $set->addManual($manual);

        $this->assertSame($set, $manual->getSet());
        $this->assertTrue($set->getManuals()->contains($manual));
    }

    public function testRemoveManualRemovesItFromTheCollection(): void
    {
        $set = new Set();
        $manual = new Manual();
        $set->addManual($manual);

        $set->removeManual($manual);

        $this->assertFalse($set->getManuals()->contains($manual));
    }
}
