version: "3"

services:

  webserver:
    container_name: lego
    image: ojooss/lema:latest
    restart: always
    volumes:
      - "./data:/var/www/html/data"
    environment:
      APP_ENV: prod
      DATABASE_URL: "sqlite:///var/www/html/data/sqlite.db"
