version: "3"

services:

  webserver:
    container_name: lego
    build:
      context: ..
    image: lego:latest
    ports:
      - "${APP_DEFAULT_PORT}:80"
    volumes:
      - "../public/data:/var/www/html/public/data"
    environment:
      APP_ENV: prod
      APP_DEFAULT_PORT: ${APP_DEFAULT_PORT}
