version: "3"

services:

  webserver:
    container_name: lego
    image: ojooss/lema:latest
    restart: always
    volumes:
      - "../public/data:/var/www/html/public/data"
    environment:
      APP_ENV: prod
