<?php

namespace App\Tests\Fake;

use App\Service\SetLookupService;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Process\Process;

/**
 * Test double for SetLookupService that never spawns the real Node/Puppeteer
 * scraper. The failure case still runs a real (but trivial and instant)
 * failing process, so ProcessFailedException behaves exactly as it would in
 * production instead of being hand-constructed.
 *
 * Generated by JetBrains AI
 */
class FakeSetLookupService extends SetLookupService
{
    private array $result = [];
    private bool $shouldFail = false;

    public function __construct()
    {
    }

    public static function returning(array $result): self
    {
        $service = new self();
        $service->result = $result;

        return $service;
    }

    public static function failing(): self
    {
        $service = new self();
        $service->shouldFail = true;

        return $service;
    }

    public function lookup(int $setNumber): array
    {
        if ($this->shouldFail) {
            $process = new Process(['php', '-r', 'exit(1);']);
            $process->run();

            throw new ProcessFailedException($process);
        }

        return $this->result;
    }
}
